server:
  port: 8088
  servlet:
   context-path: /auth-server
logging:
  level:
    root: DEBUG
  
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'